### ISSUE TITLE
[Feature]: Support OpenAPI 3.0.x

### ISSUE THREAD

**Issue by ayhanap** [PaddleHQ/paddle-openapi#3]
### Tell us about your feature request

It would be nice to have the spec file published as an OpenAPI 3.0.3 file as well.

### What problem are you looking to solve?

The tooling around OpenAPI spec 3.1 is quite low. Most generators have problems generating 3.1 spec files. I spent quite a while now yet to generate the a client for this spec in java.

### How important is this suggestion to you?

Nice to have

**Comment by Haarolean** [comment]
I double this, an issue about supporting 3.1 spec in openapi-generator has been open for **_three_** years now ([link](https://github.com/OpenAPITools/openapi-generator/issues/9083)), and I doubt we'll see it implemented any time soon.

**Comment by heymcgovern** [comment]
Hey folks 👋 Thanks for your patience here. We took a good look at porting our spec back to OpenAPI 3.0 but it's not feasible right now. We rely pretty heavily on features from OpenAPI 3.1, and rolling back to 3.0 would mean a substantial overhaul and ongoing maintenance that we can't commit to.

We're keeping an eye on demand for SDKs, so I've made a note that folks here are interested in .NET and Java 👀

I'm going to close this issue as "unplanned," but feel free to pop by with any extra context or thoughts.

**Comment by Haarolean** [comment]
Amazing, so having OpenAPI 3.0 spec is a maintenance you can't commit to, at the same time we can't have a proper SDK for java/.net. That's why you'd better shift the responsibility of dealing with your API (which is 30,000 lines long in OpenAPI spec!) on your customers/merchants who have to re-implement the same piece over and over for each of them. 

I don't see any benefits of choosing paddle over stripe (or recently acquired lemon squeezy by them, which is a merchant of record) with these questionable business decisions in consideration.

**Comment by cverhelst** [comment]
> Hey folks 👋 Thanks for your patience here. We took a good look at porting our spec back to OpenAPI 3.0 but it's not feasible right now. We rely pretty heavily on features from OpenAPI 3.1, and rolling back to 3.0 would mean a substantial overhaul and ongoing maintenance that we can't commit to.
> 
> We're keeping an eye on demand for SDKs, so I've made a note that folks here are interested in .NET and Java 👀
> 
> I'm going to close this issue as "unplanned," but feel free to pop by with any extra context or thoughts.

I appreciate the extra overhead this may cause for the team. Any option of support only a subset of the api that does not involve any of the v3.1 features?

In absence of v3.0 support, is there any alternative that may help us support the API without custom coding it ourselves in dotnet?

Right now, I've resorted to mapping the json response examples from the docs using https://quicktype.io/csharp with very loose settings (all props are optional etc) and manually fixing some of the missing values.

**Comment by ayhanap** [comment]
Here is a file that I downgraded to v3.0 manually at 29 May. I wrote down the steps which you may repeat yourself if needed (2nd file in gist).

https://gist.github.com/ayhanap/1dd580d4d88527921b46e50f9c328c27
