### ISSUE TITLE
[Bug]: Subscription edit preview not returning proration values

### ISSUE THREAD

**Issue by ayhanap** [PaddleHQ/paddle-openapi#4]
### What happened?

https://developer.paddle.com/api-reference/subscriptions/preview-subscription operation response returns `data.next_transaction.details.line_items[].proration` object but OpenAPI file nor the documentation doesn't have it. But example in OpenAPI spec has this field.

### Steps to reproduce

1) POST https://developer.paddle.com/api-reference/subscriptions/preview-subscription with any applicable values.
2) inspect the results and compare with OpenAPI file

### What did you expect to happen?

We need `data.next_transaction.details.line_items[].proration` field to decide and visualise which item is a full price item and which item is a proration.

**Comment by vijayasingam-paddle** [comment]
Hi @ayhanap,
Thank you for raising this bug report. 

We checked this issue and it appears that our documentation is missing this field. As the API is already returning the value, it will continue to work as is. 

We will update our documentation(developer documentation and API spec) to include the field.

**Comment by vijayasingam-paddle** [comment]
Hello, 
I am going to close this issue as our documentation is updated with the missing property.

Please let us know if we can help with anything else. 
Thank you.
